# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60a4566a14cfed80b0f7afec116a796cd80856669887866b2ebdbc1fc389cf15336dec31d1ae78b83bc0bfdcec12c9e325644e3a6fb2c83e2d7c412281d6299a

test:
  secret_key_base: e7b00d4ab19437d96697d26462aef957d9b1acde16f19630c736de698ebe0bc9b950369f47aa46ac5b8cfc058267aeb9a16f245709ef7bb48a8202eaa6322ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
